---
  on:
    push:
      branches:
        - main
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - edited
  permissions:
      contents: read
  jobs:
    release-draft:
      permissions:
        pull-requests: write
        contents: write
      uses: coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter.yaml@aa5c460d5c96f9963e1ad742e2fe0ae4ffc0709b
    build:
      if: always()
      needs: ['release-draft']
      runs-on: ubuntu-latest
      steps:
        - run: exit 1
          name: "Catch errors"
          if: |
            needs.release-draft.result == 'failure'