name: Draft Release
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
permissions:
  contents: read
jobs:
  release-draft:
    permissions:
      pull-requests: write
      contents: write
    uses: coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter.yaml@da683f7be5e5d3ffd8df9bdc407abd4ccd7f5029
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}