on:
  workflow_call:
    inputs:
      config-name:
        type: string
        description: >-
          Config filename. This should either be present in your repository's
          .github folder or .github repo's .github folder.
        required: false
        default: release-drafter.yml
      commitish:
        type: string
        description: >-
          Commitish to use when calculating the version bump. Defaults to the
          pull request base branch.
        required: false
        default: main
      publish:
        type: boolean
        description: Publish the release draft. Defaults to false.
        required: false
        default: false
    outputs:
      id:
        value: ${{ jobs.update-release-draft.outputs.id }}
        description: >-
          The ID of the release that was created or updated.
      name:
        value: ${{ jobs.update-release-draft.outputs.name }}
        description: >-
          The name of this release.
      tag_name:
        value: ${{ jobs.update-release-draft.outputs.tag_name }}
        description: >-
          The name of the tag associated with this release.
      body:
        value: ${{ jobs.update-release-draft.outputs.body }}
        description: >-
          The body of the drafted release, useful if it needs to be included 
          in files.
      html_url:
        value: ${{ jobs.update-release-draft.outputs.html_url }}
        type: string
        description: >-
          The URL users can navigate to in order to view the release. 
          i.e. https://github.com/octocat/Hello-World/releases/v1.0.0.
      upload_url:
        value: ${{ jobs.update-release-draft.outputs.upload_url }}
        description: >-
          The URL for uploading assets to the release, which could be 
          used by GitHub Actions for additional uses, for example the 
          @actions/upload-release-asset GitHub Action.

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    outputs:
        id: ${{ steps.update-release-draft.outputs.id }}
        name: ${{ steps.update-release-draft.outputs.name }}
        tag_name: ${{ steps.update-release-draft.outputs.tag_name }}
        body: ${{ steps.update-release-draft.outputs.body }}
        html_url: ${{ steps.update-release-draft.outputs.html_url }}
        upload_url: ${{ steps.update-release-draft.outputs.upload_url }}
    steps:
      - uses: release-drafter/release-drafter@v5.25.0
        id: update-release-draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: '${{ inputs.commitish }}'
          config-name: '${{ inputs.config-name }}'
          publish: '${{ inputs.publish }}'
