---
on:
  workflow_call:
    inputs:
      config-name:
        description: 'Config filename. This should either be present in your repository's .github folder or .github repo's .github folder.'
        required: false
        default: 'release-drafter.yml'
      commitish:
        description: 'Commitish to use when calculating the version bump. Defaults to the pull request base branch.'
        required: false
        default: 'main'
      publish:
        description: 'Publish the release draft. Defaults to false.'
        required: false
        default: 'false'
    secrets:
      GITHUB_TOKEN:
        description: 'Token'
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      # 5.24.0
      - uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ inputs.commitish }}
          config-name: ${{ inputs.config-name }}
          publish: ${{ inputs.publish }}