'on':
  workflow_call:
    inputs:
      config-name:
        description: >-
          Config filename. This should either be present in your repository's
          .github folder or .github repo's .github folder.
        required: false
        default: release-drafter.yml
      commitish:
        description: >-
          Commitish to use when calculating the version bump. Defaults to the
          pull request base branch.
        required: false
        default: main
      publish:
        description: Publish the release draft. Defaults to false.
        required: false
        default: 'false'
      go-version-file:
        type: string
        description: The path to the go.mod file
        required: false
        default: go.mod
    secrets:
      GITHUB_TOKEN:
        description: Token
        required: true
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false
jobs:
  label-pr-go:
    if: github.event_name == "pull_request"
    name: Label PR (Golang)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: '${{ inputs.go-version-file }}'
      - uses: joelanford/go-apidiff@main
        id: apidiff
        continue-on-error: true
      - uses: actions/github-script@v6
        if: github.event_name == "pull_request"
        env:
          LABEL: '${{ steps.apidiff.outputs.semver-type }}'
        with:
          script: |
            const { LABEL } = process.env;
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [`${LABEL}`]
            })
  draft-release:
    name: Draft Release
    uses: >-
      coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter.yaml@main
    secrets: inherit
    inputs:
      config-name: '${{ inputs.config-name }}'
      commitish: '${{ inputs.commitish }}'
      publish: '${{ inputs.publish }}'