name: Release Tagger
on:
  release:
    types:
      - released
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Remove old tag and tag main with vX
        run: |
          git fetch --all
          git checkout main

          # Extract vX from vX.Y.Z
          NEW_TAG=$(echo "${{ github.event.release.tag_name }}" | cut -d'.' -f1)

          # Create new tag
          git tag -f $NEW_TAG -m "Forcing tag to match release"
          git push origin -f $NEW_TAG
